<<<<<<< HEAD
version: "3.9"
services:
  flask_compose:
    build:
      dockerfile: giovannymtz11/flaskapp:latest
    ports:
      - "5050:5050"
    links:
      - databaseserver
  databaseserver:
    build:
      dockerfile: giovannymtz11/dbapp:latest
    ports:
      - "3303:3303"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=itl
=======
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DB=itl

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

>>>>>>> bba1099 (Dockerizacion exitosa)

